#!/bin/sh
#
# PROVIDE: zerodns
# REQUIRE: DAEMON NETWORKING FILESYSTEMS
# BEFORE: LOGIN
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable zerodns:
#
# zerodns_enable="YES"
#

. /etc/rc.subr

name="zerodns"
desc="ZeroDNS daemon"
rcvar=zerodns_enable
required_modules="pty"

load_rc_config ${name}

: ${zerodns_enable="NO"}
: ${zerodns_network="any"}
: ${zerodns_user="zerodns"}
: ${zerodns_group="zerodns"}

command="/usr/local/bin/zero-dns"
command_args="-n ${zerodns_network} -d ${zerodns_iface}"

run_rc_command "$1"
