#!/bin/sh
#
# PROVIDE: zerodns
# KEYWORD: nojailvnet nostart shutdown
#

. /etc/rc.subr
. /etc/network.subr

ifn="$2"

name="zerodns"
desc="ZeroDNS daemon"
rcvar=
required_modules="pty"

load_rc_config ${name}
load_rc_config network

: ${zerodns_user="zerodns"}
: ${zerodns_group="zerodns"}

command="/usr/local/bin/zero-dns"
command_args="-d ${ifn}"

run_rc_command "$1"
